Update git-verify_committers-roush_dev.py
When commit message blank TypeError thrown because GIT_COMMIT_MSG_BODY set to None.

+ /home/jenkins/jenkins-build/git-verify_committers-roush_dev.py
Traceback (most recent call last):
  File "/home/jenkins/jenkins-build/git-verify_committers-roush_dev.py", line 78, in <module>
    rallyid = _check_for_rallyid(GIT_COMMIT_MSG_BODY)
  File "/home/jenkins/jenkins-build/git-verify_committers-roush_dev.py", line 25, in _check_for_rallyid
    match = re.match(pattern, msg)
  File "/usr/lib/python2.6/re.py", line 137, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or buffer