Use patch files instead of diff files for binaries
PR requests with binary additions will fail to apply the diff with the
following error:

  error: cannot apply binary patch to '...' without full index line

The patch supplied by github has all the requisit information that the
diff is missing.

- use the PATCH_URL instead of the DIFF_URL